swagger: '2.0'
info:
  description: 'This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.'
  version: 1.0.0
  title: Swagger Petstore
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache-2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
# host: "petstore.swagger.io"
basePath: '/'
schemes:
  # tip: remove http to make production-grade
  - http
  # - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
################################################################################
#                                  Security Defenitions                        #
################################################################################
securityDefinitions:
  JWT:
    type: apiKey
    name: Authorization
    in: header
    description: |
     For accessing the API a valid JWT token must be passed in all the queries in
     the 'Authorization' header.  
     A valid JWT token is generated by the API and retourned as answer of a call
     to the route /login giving a valid user & password.  
     The following syntax must be used in the 'Authorization' header :
  
         Bearer xxxxxx.yyyyyyy.zzzzzz
################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  path-id:
    $ref: ./swagger/parameters/path-id.yaml
################################################################################
#                                   Routes                                     #
################################################################################
paths:
  #-----------------------------------------------------------------------------
  # Pets
  /pets/:
    $ref: ./swagger/paths/pets/.yaml
  /pets/{id}:
    $ref: ./swagger/paths/pets/id.yaml
################################################################################
#                                   Defenitions                                #
################################################################################
x-swagger-mongoose:
  schema-options:
    timestamps: true
definitions:
  Pet:
    $ref: ./swagger/definitions/Pet.yaml